name: Deploy to remote server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent manually
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519
          ssh-keyscan -H 159.223.150.26 >> ~/.ssh/known_hosts





      - name: Run deploy commands
        run: |
          ssh -o StrictHostKeyChecking=no deploy@159.223.150.26 << 'EOF'
            cd /home/deploy/app
            git pull origin main
            docker compose up -d --build
          EOF
